version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: synapse-be
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: synapse-fe
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
